### ISSUE TITLE
Make the Documentation More Comprehensive?

### ISSUE THREAD

**Issue by KarenEfereyan** [EddieJaoudeCommunity/gh-action-community#36]
@eddiejaoude Maybe we could make the documentation a little bit more encompassing?

**Comment by eddiejaoude** [comment]
Yes you are right, the documentation needs improving.

I wanted to check it worked first, then when we start using it in other repos in our organisation, we can improve the documentation

**Comment by KarenEfereyan** [comment]
Sure, I can contribute in any way needed

**Comment by eddiejaoude** [comment]
Thank you 👍

**Comment by eddiejaoude** [comment]
I have added some documentation. I will close this for now but feel free to create a new Issue for anything is missing
