### ISSUE TITLE
Check if Firebase key exists before running statistics action

### ISSUE THREAD

**Issue by alrifay** [EddieJaoudeCommunity/gh-action-community#42]
It will make testing `community.yml` easier

**Comment by eddiejaoude** [comment]
Yep good idea, I will have to figure out how to check an `input` in the yaml

**Comment by eddiejaoude** [comment]
I couldn't figure out how to do this in the condition. I am not sure if this is still needed now as I changed the event types. 

Shall we close for now and reopen if required in the future @alrifay ?

**Comment by eddiejaoude** [comment]
Slowly moving to Mongo too 🎉 - I am tempted to close this, what do people think?

**Comment by Vyvy-vi** [comment]
yeah shifting to mongo would be great.

**Comment by eddiejaoude** [comment]
There is a PR open already. The current plan is to have an API that uses mongo, so that our other repos only have to use an API https://github.com/EddieJaoudeCommunity/EddieCommunityApi/pull/5
