### ISSUE TITLE
Comment message name

### ISSUE THREAD

**Issue by vj-abishek** [EddieJaoudeCommunity/gh-action-community#60]
There should be `github-actions` name or the person's `name` when a person is invited to an organization 

[Here you can find a demo message](https://github.com/vj-abigo/invites/issues/5)

**Comment by eddiejaoude** [comment]
@vj-abishek did you mean to close this?

**Comment by vj-abishek** [comment]
Sorry that issue was solved 😅. I asked " the reply for organization invitation should be bot message or real human"

**Comment by eddiejaoude** [comment]
ah ok, no problem 👍
